apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  name: example-distributedrediscluster
spec:
  image: uhub.service.ucloud.cn/operator/redis:5.0.4-alpine
  masterSize: 3
  clusterReplicas: 1
  monitor:
    image: oliver006/redis_exporter